{% set version = "1.6.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  fn: lidR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lidR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: 42b98424630d14a6972b4a923344003a8d4c167e6c8fd021e803f2caf9d2ad14

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rann
    - r-rcpp
    - r-assertive
    - r-concaveman
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-glue
    - r-gstat
    - r-lazyeval
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.10
    - r-settings
    - r-sp
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rann
    - r-rcpp
    - r-assertive
    - r-concaveman
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-glue
    - r-gstat
    - r-lazyeval
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.10
    - r-settings
    - r-sp

test:
  commands:
    - $R -e "library('lidR')"  # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://cran.r-project.org/package=lidR
  license: GPL-3
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization.
    Read/write 'las' and 'laz' files, computation of metrics in area based approach,
    point filtering, artificial point reduction, classification from geographic data,
    normalization, individual tree segmentation and other manipulations.

extra:
  recipe-maintainers:
    - ocefpaf
