{% set version = "2.1.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lidR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: 422bb493575ceb1597a6a162e461da8e7a1f8958968198310e7df9028dcbc262

build:
  merge_build_host: True  # [win]
  number: 0
  script: R CMD INSTALL --build .
  # no r-rgl on osx
  skip: True  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rann
    - r-rcpp
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-gstat
    - r-lazyeval
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.10
    - r-settings
    - r-sp
  run:
    - r-base
    - r-rann
    - r-rcpp
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-gstat
    - r-lazyeval
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.10
    - r-settings
    - r-sp

test:
  commands:
    - $R -e "library('lidR')"  # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://cran.r-project.org/package=lidR
  license: GPL-3
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization.
    Read/write 'las' and 'laz' files, computation of metrics in area based approach,
    point filtering, artificial point reduction, classification from geographic data,
    normalization, individual tree segmentation and other manipulations.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
