{% set version = "4.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lidR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: 9380ca5538ef30f369d2ef640e51e92e1d87c13b3a3c7fe39e6f46b3edf3a57d
  patches:
    ## this is from upstream, so expect to drop next release
    - patches/0001-cxx14-win.patch

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh >=1.72.0
    - r-classint
    - r-data.table >=1.12.0
    - r-glue
    - r-lazyeval
    - r-raster
    - r-rcpp >=1.0.3
    - r-rcpparmadillo
    - r-rgl
    - r-rlas >=1.5.0
    - r-sf
    - r-sp
    - r-stars
    - r-terra >=1.5_17
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-classint
    - r-data.table >=1.12.0
    - r-glue
    - r-lazyeval
    - r-raster
    - r-rcpp >=1.0.3
    - r-rcpparmadillo
    - r-rgl
    - r-rlas >=1.5.0
    - r-sf
    - r-sp
    - r-stars
    - r-terra >=1.5_17

test:
  commands:
    - $R -e "library('lidR')"           # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://github.com/Jean-Romain/lidR
  license: GPL-3.0-only
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization. Read/write 'las' and 'laz' files, computation of metrics in area based approach, point filtering, artificial point reduction, classification from geographic data, normalization, individual tree segmentation and other
    manipulations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
