{% set version = "4.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lidR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: 025c15a772371b532397e7412c42382f9f4bc6909e2aa1c740b37cdf5e190dd2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh >=1.72.0
    - r-rcpp >=1.0.3
    - r-rcpparmadillo
    - r-rnanoflann
    - r-classint
    - r-data.table >=1.12.0
    - r-glue
    - r-lazyeval
    - r-rgl
    - r-rlas >=1.8.2
    - r-sf
    - r-stars
    - r-terra >=1.5_17
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    #- r-bh >=1.72.0
    - r-rcpp >=1.0.3
    - r-rcpparmadillo
    - r-rnanoflann
    - r-classint
    - r-data.table >=1.12.0
    - r-glue
    - r-lazyeval
    - r-rgl
    - r-rlas >=1.8.2
    - r-sf
    - r-stars
    - r-terra >=1.5_17

test:
  commands:
    - $R -e "library('lidR')"           # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://github.com/Jean-Romain/lidR
  license: GPL-3.0-only
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization. Read/write 'las' and 'laz' files, computation of metrics in area based approach, point filtering, artificial point reduction, classification from geographic data, normalization, individual tree segmentation and other
    manipulations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
