{% set version = "1.4.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  fn: lidR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lidR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: 61611c0931216de7a0c26da718ef8d497826bad51d62babcfa29cdd64e34dc06

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rann
    - r-rcpp
    - r-rcppprogress
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-gstat
    - r-lazyeval
    - r-magrittr
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.6
    - r-settings
    - r-sp
    - r-stringr
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]
  run:
    - r-base
    - r-rann
    - r-rcpp
    - r-rcppprogress
    - r-data.table
    - r-future
    - r-gdalutils
    - r-geometry
    - r-gstat
    - r-lazyeval
    - r-magrittr
    - r-mapedit
    - r-mapview
    - r-memoise
    - r-raster
    - r-rgeos
    - r-rgl
    - r-rlas >=1.1.6
    - r-settings
    - r-sp
    - r-stringr
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('lidR')"  # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://cran.r-project.org/package=lidR
  license: GPL-3
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization.
    Read/write 'las' and 'laz' files, computation of metrics in area based approach,
    point filtering, artificial point reduction, classification from geographic data,
    normalization, individual tree segmentation and other manipulations.

extra:
  recipe-maintainers:
    - ocefpaf
