{% set version = '2.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lidr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lidR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lidR/lidR_{{ version }}.tar.gz
  sha256: fe851a0522fc9350145da4e912d9c895a13b4ba59340f487e00d4038276e372b

build:
  merge_build_host: True  # [win]
  number: 0
  # no r-rgl on osx
  skip: True  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcsf
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-data.table >=1.12.0
    - r-future
    - r-gdalutils
    - r-geometry
    - r-glue
    - r-imager
    - r-lazyeval
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-rgl
    - r-rlas >=1.3.0
    - r-sf
    - r-sp
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rcsf
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-data.table >=1.12.0
    - r-future
    - r-gdalutils
    - r-geometry
    - r-glue
    - r-imager
    - r-lazyeval
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-rgl
    - r-rlas >=1.3.0
    - r-sf
    - r-sp

test:
  commands:
    - $R -e "library('lidR')"           # [not win]
    - "\"%R%\" -e \"library('lidR')\""  # [win]

about:
  home: https://github.com/Jean-Romain/lidR
  license: GPL-3
  summary: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization.
    Read/write 'las' and 'laz' files, computation of metrics in area based approach,
    point filtering, artificial point reduction, classification from geographic data,
    normalization, individual tree segmentation and other manipulations.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: lidR
# Type: Package
# Title: Airborne LiDAR Data Manipulation and Visualization for Forestry Applications
# Version: 2.1.3
# Date: 2019-09-09
# Authors@R: c( person("Jean-Romain", "Roussel", email = "jean-romain.roussel.1@ulaval.ca", role = c("aut", "cre", "cph")), person("David", "Auty", email = "", role = c("aut", "ctb"), comment = "Reviews the documentation"), person("Florian", "De Boissieu", email = "", role = ("ctb"), comment = "Fixed bugs and improved catalog features"), person("Andrew", "Sanchez Meador", email = "", role = ("ctb"), comment = "Implemented lassnags"))
# Description: Airborne LiDAR (Light Detection and Ranging) interface for data manipulation and visualization. Read/write 'las' and 'laz' files, computation of metrics in area based approach, point filtering, artificial point reduction, classification from geographic data, normalization, individual tree segmentation and other manipulations.
# URL: https://github.com/Jean-Romain/lidR
# BugReports: https://github.com/Jean-Romain/lidR/issues
# License: GPL-3
# Depends: R (>= 3.1.0),methods,raster,sp
# Imports: data.table (>= 1.12.0), future, gdalUtils, geometry, glue, grDevices, lazyeval, imager, Rcpp (>= 0.11.0), RCSF, rgeos, rgdal, rgl, rlas (>= 1.3.0), sf, stats, tools, utils
# Suggests: EBImage, concaveman, crayon, gstat, hexbin, mapview, mapedit, progress, testthat (>= 2.1.0), knitr, rmarkdown
# LazyData: true
# RoxygenNote: 6.1.1
# LinkingTo: BH,Rcpp,RcppArmadillo
# Encoding: UTF-8
# ByteCompile: true
# VignetteBuilder: knitr
# Collate: 'Class-LASheader.r' 'Class-LAS.r' 'Class-LAScatalog.r' 'Class-LAScluster.r' 'RcppExports.R' 'algorithm-dec.r' 'algorithm-dsm.r' 'algorithm-gnd.r' 'algorithm-itd.R' 'algorithm-its.r' 'algorithm-shp.r' 'algorithm-snag.r' 'algorithm-spi.r' 'catalog_apply.r' 'catalog_fakerun.r' 'catalog_index.r' 'catalog_intersect.r' 'catalog_laxindex.r' 'catalog_makecluster.r' 'catalog_merge_results.R' 'catalog_retile.r' 'catalog_select.r' 'clusters_apply.r' 'doc-drivers.R' 'doc-lidR.R' 'doc-parallelism.R' 'grid_canopy.r' 'grid_density.r' 'grid_hexametrics.r' 'grid_metrics.r' 'grid_metrics3d.r' 'grid_terrain.r' 'io_readLAS.r' 'io_readLAScatalog.r' 'io_writeANY.r' 'io_writeLAS.r' 'lascheck.r' 'lasclip.r' 'lasdetectshape.r' 'lasfilter.r' 'lasfilterdecimate.r' 'lasfilterduplicates.r' 'lasfiltersurfacepoints.r' 'lasground.r' 'lasindentify.r' 'lasmergelas.r' 'lasmergespatial.r' 'lasmetrics.r' 'lasnormalize.r' 'lasrescale.R' 'lasroi.r' 'lassmooth.r' 'lassnags.r' 'lastransform.r' 'lastrees.r' 'lasupdateheader.r' 'lasvoxelize.r' 'methods-LAS.r' 'methods-LAScatalog.r' 'methods-LAScluster.r' 'methods-LASheader.r' 'plot.r' 'plot.s3.r' 'print.r' 'projection.r' 'tree_detection.r' 'tree_hulls.r' 'tree_metrics.r' 'utils_assertive.r' 'utils_catalog_options.r' 'utils_colors.r' 'utils_define_constant.R' 'utils_delaunay.R' 'utils_geometry.r' 'utils_is.r' 'utils_metrics.r' 'utils_misc.r' 'utils_raster.r' 'utils_threads.r' 'utils_typecast.r' 'zzz.r'
# NeedsCompilation: yes
# Packaged: 2019-09-10 15:30:40 UTC; jr
# Author: Jean-Romain Roussel [aut, cre, cph], David Auty [aut, ctb] (Reviews the documentation), Florian De Boissieu [ctb] (Fixed bugs and improved catalog features), Andrew Sanchez Meador [ctb] (Implemented lassnags)
# Maintainer: Jean-Romain Roussel <jean-romain.roussel.1@ulaval.ca>
# Repository: CRAN
# Date/Publication: 2019-09-10 16:20:05 UTC
